# Web service for simple nodejs Hello World
apiVersion: v1
kind: Service
metadata:
  name: nodejs
  labels:
    app: nodejs
spec:
  ports:
  - name: nodejs
    port: 80
  clusterIP: None
  selector:
    app: nodejs
