# Service for simple nodejs Hello World
apiVersion: v1
kind: Service
metadata:
  name: nodejs
  labels:
    app: nodejs
spec:
  selector:
    app: nodejs
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080

